LLM_USAGE_DATABASE_PATH = "llm_usage.db"

DEFAULT_GAME_ID = "default_game"
DEFAULT_PHASE_NAME = "default_phase"
LLM_CALL_REQUEST_ID_DEFAULT = "default_request_id"
LOCAL_LLM_SERIAL_ACCESS_PREFIXES = ("local/", "ollama/", "llamacpp/")

LLM_CALL_RESULT_ERROR_NOT_INITIALIZED = "LLM_NOT_INITIALIZED"
LLM_CALL_ERROR_EMPTY_RESPONSE = "EMPTY_LLM_RESPONSE"
LLM_CALL_LOG_RESPONSE_TYPE_DEFAULT = "llm_response"
MAX_CONTENT_LOG_LENGTH = 500

DEFAULT_TURN_NUMBER = -1
DEFAULT_PLAYER_NAME = "N/A"
