# Configuration file for assigning LLM models to Diplomacy powers.

# Optional: Default model to use if a power is not explicitly listed below,
# or if a specified model is found to be invalid/unavailable during agent initialization.
# If commented out or missing, AgentManager might use its own hardcoded fallback.
default_model = "gemma3:4b" # Example: a generally available local model

# --- Power-Specific Model Assignments ---
# List each power and the llm-compatible model ID you want it to use.
# For Ollama models, use the model name directly (e.g., "llama3:latest", "gemma3:4b").
# API-based models should use their standard identifiers (e.g., "gpt-4o", "claude-3-opus-20240229").
# Make sure any necessary API keys (OPENAI_API_KEY, ANTHROPIC_API_KEY, etc.) are set in your environment
# or .env file, and that the `llm` library has the required plugins installed.

[powers]
AUSTRIA = "gemma3:12b"
ENGLAND = "llama3:latest" # Using available Ollama model
FRANCE = "gemma3:12b"
GERMANY = "gemma3:4b" # Using available Ollama model
ITALY = "gemma3:12b"
RUSSIA = "gemma3:4b"    # Using available Ollama model
TURKEY = "gemma3:4b" # Using available Ollama model

# Example of how you might comment out a power to let it use the default_model:
# ENGLAND = "ollama/codellama:7b-instruct"
# GERMANY = # This would make Germany use default_model (if one is defined) or AgentManager's fallback

# --- Advanced: Model Profiles (Illustrative - Not yet fully implemented in coordinator for per-model host/port) ---
# This section is a placeholder for future enhancements if you need to specify
# more than just the model ID (e.g., different Ollama server URLs per model).
# Currently, the llm_coordinator uses the globally configured OLLAMA_HOST for all ollama models.

# [model_profiles.ollama_server_A_mistral]
# provider = "ollama"
# model_id = "ollama/mistral"
# base_url = "http://localhost:11435/api" # Example for a different Ollama instance

# [model_profiles.openai_gpt4_turbo]
# provider = "openai"
# model_id = "gpt-4-turbo"

# And then in [powers] you might reference them:
# GERMANY = { profile = "ollama_server_A_mistral" }
# AUSTRIA = { profile = "openai_gpt4_turbo" } 