# Game Configuration for WWI Two-Player Scenario

[scenario]
name = "wwi_two_player_test"
game_factory = "scenarios.wwi_two_player" # Points to the function

[game_settings]
game_id_prefix = "wwi_test"
perform_planning_phase = false
num_negotiation_rounds = 2
negotiation_style = "simultaneous"
max_years = 1903 # Short game for testing
max_diary_tokens = 6000

[logging]
log_level = "INFO"
log_to_file = true
# base_log_dir = "logs/wwi_scenario_logs" # User can customize

[dev_settings]
dev_mode = false
verbose_llm_debug = true

# Agent definitions for the WWI scenario
# The order of agents in this list (e.g., Entente, Central, Italy) is important
# as lm_game.py's wwi_two_player factory consumes them in that specific order.
# 1. Entente
# 2. Central
# 3. Italy (Null)
agents = [
    { id = "ENTENTE_POWERS", type = "bloc_llm", model = "gpt-4-turbo", powers = ["ENGLAND", "FRANCE", "RUSSIA"] },
    { id = "CENTRAL_POWERS", type = "bloc_llm", model = "gemma3:12b", powers = ["AUSTRIA", "GERMANY", "TURKEY"] },
    { id = "ITALY_NULL_AGENT", type = "null", country = "ITALY" } # Italy controlled by NullAgent
    # No model needed for "null" type. 'country' specifies the power it controls.
]

# Example of how power-specific models could be overridden if models.toml is also used
# This is separate from the main game config TOML.
# [models_override] 
# ENGLAND = "specific_model_for_england" 