name: Python CI with uv and ruff

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13'] # Specify stable Python versions
        # Add '3.13' or '3.13-dev' if you really need to test against pre-releases.
        # Example: python-version: ['3.11', '3.12', '3.13']
      fail-fast: false # Don't cancel all jobs if one Python version fails

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
   
    - name: Set up uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"
        
    - name: Install the project
      run: uv sync --dev
    
    #- name: Lint with Ruff
     # uses: astral-sh/ruff-action@v3
     # with:
     #   args: "check --diff . && ruff format --check --diff ."

    - name: Run unit tests with pytest
      run: |
        uv run pytest -q
