name: Python Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        pip install uv
        uv pip install -p pyproject.toml
        uv pip install pytest

    - name: Test with pytest
      run: |
        pytest 